# v2 syntax
version: '2'
services:
  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: workoutPlan-db
    volumes:
      - ./.data/db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=api
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root

  # PHP (with Nginx)
  app:
    image: ambientum/php:7.2-nginx
    container_name: workoutPlan-api
    volumes:
      - .:/var/www/app
    ports:
      - "8000:8080"
    links:
      - mysql